export const ADD_NEW_ISSUE = 'ADD_NEW_ISSUE';
export const ADD_PERSON_TO_TASK = 'ADD_PERSON_TO_TASK';
export const CHANGE_HAPPINESS = 'CHANGE_HAPPINESS';
export const CREATE_PEOPLE = 'CREATE_PEOPLE';
export const CHANGE_WORK = 'CHANGE_WORK';
export const DESERIALIZE = 'DESERIALIZE';
export const GAME_FREEZE = 'GAME_FREEZE';
export const GAME_UNFREEZE = 'GAME_UNFREEZE';
export const HIRE_PERSON = 'HIRE_PERSON';
export const NEXT_TURN = 'NEXT_TURN';
export const REMOVE_PERSON_FROM_TASK = 'REMOVE_PERSON_FROM_TASK';
export const SCENE_CHANGE = 'SCENE_CHANGE';
export const SERIALIZE = 'SERIALIZE';
export const START_GAME = 'START_GAME';
export const TOGGLE_PERSON_AREA = 'TOGGLE_PERSON_AREA';

